name: Hugo-CI
on:
  pull_request:
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, hugo-dev-dev4]
    steps:
      - name: hugo build
        run: |
          filename=${{github.head_ref}}
          dirname=${filename#*/}
          content_parent_dir=`echo $dirname |sed 's/\/.*//'`
          cd /home/valeriyten/distr/hugo-build-dev/html-test/ && git stash && git pull
          rm -rf /home/valeriyten/distr/hugo-build-dev/lutsk-aspose-prototype/content/* && rm -rf /home/valeriyten/distr/hugo-build-dev/lutsk-aspose-prototype/public/*
          rsync --progress -r $content_parent_dir/ /home/valeriyten/distr/hugo-build-dev/lutsk-aspose-prototype/content/$content_parent_dir/ --delete && cd /home/valeriyten/distr/hugo-build-dev/lutsk-aspose-prototype/ && hugo
