name: Hugo-CI
on:
  pull_request:
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, hugo-dev-dev4]
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Hugo build
        run: |
          filename=${{github.head_ref}}
          dirname=${filename#*/}
          content_parent_dir=`echo $dirname |sed 's/\/.*//'`
          dir1=${filename%/*}
          dir2=${dir1##*/}
          final_directory="${content_parent_dir}/${dir2}"
