name: Hugo-CI
on:
  pull_request:
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, hugo-dev-dev4]
    steps:
      - name: hugo build
        run: |
          ls
