name: Hugo-CI
on:
  pull_request:
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, hugo-dev-dev4]
    steps:
      - name: hugo build
        run: |
          ls
          filename_pre=`echo ${{ github.event.pull_request.title }}| grep -oP '(?<=.Page .).+(?=.)'` && filename_replace="index" && filename_after="${filename_pre/_index/$filename_replace}"
          echo $filename_pre
